name: Test mixed inputs

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tag:
        description: 'Name of the release TAG'
        required: true
        type: string
      push_to_package:
        required: true
        type: boolean
        default: false

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAG"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAG: ${{ inputs.tag }}
          PUSH: ${{ inputs.push_to_package}}
